/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioninscription;
import java.awt.Color;
import java.awt.Label;
import java.sql.*;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import sql.*;
import gestionrentabilite.*;
import gestionsessions.*;
/**
 *
 * @author Administrateur
 */
public class FenInscription extends javax.swing.JFrame {

    /**
     * Creates new form FenInscription
     */
    Connection conn;
    Statement stmt1, stmt2;
    
    public FenInscription()
    {
        initComponents();
        btnInscription.setVisible(false); // On rend le bouton inscription non visible
        tInscription.selectAll();
        tInscription.setDefaultRenderer(Object.class, new Couleur()); // Pour mettre les sessions déficitaires en rouge
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitre = new javax.swing.JLabel();
        lblMatricule = new javax.swing.JLabel();
        cbxMatricule = new javax.swing.JComboBox();
        lblSessionAut = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tInscription = new javax.swing.JTable();
        btnInscription = new javax.swing.JButton();
        lblSelection = new javax.swing.JLabel();
        btnGestionRentabilite = new javax.swing.JButton();
        btnGestionSession = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inscription des clients aux différentes sessions");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("GESTION DES INSCRIPTIONS");
        lblTitre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblMatricule.setText("Matricule : ");

        cbxMatricule.setName("cmbMat"); // NOI18N
        cbxMatricule.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMatriculeItemStateChanged(evt);
            }
        });

        lblSessionAut.setText(" ");
        lblSessionAut.setName("lblNomPren"); // NOI18N

        tInscription.setModel(new ModeleJTableListeSession());
        tInscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tInscriptionMouseClicked(evt);
            }
        });
        tInscription.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tInscriptionInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tInscription);

        btnInscription.setText("Inscription");
        btnInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriptionActionPerformed(evt);
            }
        });

        lblSelection.setText("Sélection : ");

        btnGestionRentabilite.setText("Gestion de Rentabilité");
        btnGestionRentabilite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionRentabiliteActionPerformed(evt);
            }
        });

        btnGestionSession.setText("Gestion de Sessions");
        btnGestionSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblSessionAut, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(572, 572, 572))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(lblSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGestionRentabilite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInscription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGestionSession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSessionAut, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionRentabilite)
                .addGap(18, 18, 18)
                .addComponent(btnGestionSession)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            try
            {
                // On prévoit 2 connexions à la base
                stmt1 = GestionBdd.connexionBdd(GestionBdd.TYPE_MYSQL, "formarmor","localhost", "root","");
                stmt2 = GestionBdd.connexionBdd(GestionBdd.TYPE_MYSQL, "formarmor","localhost", "root","");
                // Liste des clients qui "ont un plan de formation"
                String req = "select distinct c.id from client c, plan_formation p "
                 + "where c.id = p.id order by c.id";
                ResultSet rs = GestionBdd.envoiRequeteLMD(stmt1,req);
                cbxMatricule.addItem("---");
                while (rs.next())
                {
                    cbxMatricule.addItem(rs.getString(1));
                }
            }
            catch (SQLException se)
            {
                System.out.println("Erreur SQL1 : " + se.getMessage());
            }
    }//GEN-LAST:event_formWindowOpened

    private void cbxMatriculeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMatriculeItemStateChanged
          // Affichage du nom prénom et de la liste des sessions autorisées
        if (evt.getStateChange() != 1) // Pour éviter le déclenchement sur la création de la fenêtre
        {
            renseigne();
		
        }
    }//GEN-LAST:event_cbxMatriculeItemStateChanged

    private void btnInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriptionActionPerformed
        FenConfirmationInscription f2 = new FenConfirmationInscription(this, true);
        f2.init(cbxMatricule.getSelectedItem(), tInscription.getValueAt(tInscription.getSelectedRow(),0));
        f2.setSize(400,300);
        f2.setVisible(true);
    }//GEN-LAST:event_btnInscriptionActionPerformed

    private void tInscriptionInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tInscriptionInputMethodTextChanged
        //
    }//GEN-LAST:event_tInscriptionInputMethodTextChanged

    private void tInscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tInscriptionMouseClicked
        if (cbxMatricule.getSelectedIndex()>0 && tInscription.getValueAt(tInscription.getSelectedRow(), 0) != null)
        {
            lblSelection.setText(tInscription.getValueAt(tInscription.getSelectedRow(), 0).toString());
            int pos1 = lblSessionAut.getText().indexOf(":");
            String nomPrenom = lblSessionAut.getText().substring(pos1 + 1);
            btnInscription.setText("Inscription à la session numéro " + tInscription.getValueAt(tInscription.getSelectedRow(), 0) + " pour " + nomPrenom);
            btnInscription.setVisible(true);
        }
        else
        {
            btnInscription.setVisible(false);
            lblSelection.setText("Aucune sélection");
        }
    }//GEN-LAST:event_tInscriptionMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        renseigne();
    }//GEN-LAST:event_formWindowActivated

    private void btnGestionRentabiliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionRentabiliteActionPerformed
        FGestionRentabilite fGestionRentabilite = new FGestionRentabilite();
        this.setVisible(false);
        fGestionRentabilite.setVisible(true);
    }//GEN-LAST:event_btnGestionRentabiliteActionPerformed

    private void btnGestionSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionSessionActionPerformed
        FGestionSessions fGestionSessions = new FGestionSessions();
        this.setVisible(false);
        fGestionSessions.setVisible(true);
    }//GEN-LAST:event_btnGestionSessionActionPerformed
    private void renseigne()
    {
        try
        {
        // On vide le JTable
            int j, k;
            String req;
            for(int i=0;i<tInscription.getRowCount();i++)
            {
                for (j=0;j<tInscription.getColumnCount();j++)
		{
                    tInscription.setValueAt(null,i,j);
		}
            }
            if (cbxMatricule.getSelectedIndex()==0 || cbxMatricule.getSelectedItem()== null) // Pas de client de choisi
            {
                lblSessionAut.setText("ENSEMBLE DES SESSIONS");
                // Toutes les sessions
                req = "select null, s.id, f.libelle, f.niveau, date_debut, duree, nb_places, nb_inscrits, coutrevient ";
                req += "from session_formation s, formation f ";
                req += "where s.formation_id = f.id";
                // et date supérieure à la date du jour
                btnInscription.setVisible(false); // On rend le bouton inscription non visible
            }
            else
            {
                // Sélection des sessions "autorisées"
                req = "select c.nom, s.id, f.libelle, f.niveau, date_debut, duree, nb_places, nb_inscrits, coutrevient ";
                req += "from session_formation s, client c, plan_formation p, formation f ";
                req += "where c.id = '" + cbxMatricule.getSelectedItem() + "' ";
                req += "and p.client_id = c.id and nb_places > nb_inscrits ";
                req += "and p.formation_id = f.id ";
                req += "and s.formation_id = f.id ";
                // et date supérieure à la date du jour
                req += "and close = 0 and effectue = 0 and s.id Not In ";
                req += "(Select session_formation_id From inscription Where id = '" + cbxMatricule.getSelectedItem() + "')";
                if (tInscription.getValueAt(tInscription.getSelectedRow(), 0) != null) //Si la cellule sélectionnée est vide
                {
                    btnInscription.setVisible(false); // On rend le bouton inscription non visible
                }
            }
            stmt1 = GestionBdd.connexionBdd(GestionBdd.TYPE_MYSQL, "formarmor","localhost", "root","");
            ResultSet rs2 = GestionBdd.envoiRequeteLMD(stmt1, req);
            ResultSet rs3 = null;
            
            k = 0;
            try
            {
                while(rs2.next())
                {
                    if (k==0 && cbxMatricule.getSelectedIndex()!=0)
                    {
                        lblSessionAut.setText("Sessions autorisées pour : " + rs2.getString(1));
                    }
                    // On calcule la marge et on renseigne la dernière colonne(7ème) du jTable
                    req = "Select sum(taux_horaire) as revenu_session ";
                    req += "from statut st, session_formation s, client c, inscription i ";
                    req += "where s.id = i.session_formation_id and c.id = i.client_id ";
                    req += "and c.statut_id = st.id and s.id = " + rs2.getInt(2);
                    stmt2 = GestionBdd.connexionBdd(GestionBdd.TYPE_MYSQL, "formarmor","localhost", "root","");
                    rs3 = GestionBdd.envoiRequeteLMD(stmt2, req);
                    rs3.first();
                    tInscription.setValueAt((rs3.getFloat(1) - rs2.getFloat(9)), k, 7);
                    // On renseigne le reste du jTable
                    for (j=0;j<(tInscription.getColumnCount() -1);j++)
                    {
                        tInscription.setValueAt(rs2.getObject(j+2), k, j);
                    }
                    k++;
                }
                rs2.close();
            }
            catch (SQLException sqle)
            {
                System.out.print("Erreur SQL : " + sqle.getMessage());
            }
        }
        catch(NullPointerException npe)
        {
            System.out.println("Erreur : " + npe.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionRentabilite;
    private javax.swing.JButton btnGestionSession;
    private javax.swing.JButton btnInscription;
    private javax.swing.JComboBox cbxMatricule;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMatricule;
    private javax.swing.JLabel lblSelection;
    private javax.swing.JLabel lblSessionAut;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JTable tInscription;
    // End of variables declaration//GEN-END:variables
}
